[package]
name = "handmade"
version = "0.1.0"
authors = ["coeuvre"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"

[dependencies.base]
path = "../base"

[dependencies.software_renderer]
path = "../software_renderer"
