[package]
name = "handmade"
version = "0.1.0"
authors = ["coeuvre"]

[dependencies]

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = [
    "dsound",
    "libloaderapi",
    "profileapi",
    "memoryapi",
    "winerror",
    "winuser",
    "wingdi",
    "xinput"
]
